server.port: 1111
spring:
  application.name: config
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      name: config
      server:
        native:
         searchLocations: /opt/config/{application}
        default-label: trunk
    consul:
      host: 192.168.232.128
      port: 8500
      enabled: true
      discovery:
        enabled: true
        hostname: 192.168.232.128
        healthCheckInterval: 10s
